#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          motorTray,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot()
{
  //servo[servo1] = 0;  // Gripper opened
  nMotorPIDSpeedCtrl[motorTray] = mtrSpeedReg;
 	motor[motorTray] = 0;
  return;
}

void fireLauncher(){
	//start tire motors, and lower servo
	motor[motorA] = 100;
	motor[motorB] = 100;
	servo[servo1] = 255;
	wait1Msec(500);

	//stop tire motors, and reset servo
	motor[motorA] = 0;
	motor[motorB] = 0;
	servo[servo1] = 0;
}

void servoLower(int seconds){
	double ratio = 120/seconds;
	ClearTimer(T1);
	while(time1[T1] < seconds*1000){
		int timed = (int)(time1[T1]/1000);
		int temp = (int)(ratio*timed);
		servo[servo1] = temp;
	}
}

task main()
{
  initializeRobot();

  bool isLaunching = false;
  bool isDropping = false;
  int mThreshold = 15;      // Sets dead zones to avoid unnecessary movement
  int aThreshold = 30;
  int xVal, yVal;           //Stores left analog stick values
  float scaleFactor = 40.0 / 127;           //Sets max. average motor power and maps range of analog stick to desired range of power

  //waitForStart();   // wait for start of tele-op phase

  while (true)
  {
    getJoystickSettings(joystick); // Retrieves data from the joystick

    xVal = joystick.joy1_x1;
    yVal = joystick.joy1_y1;

    //Checks if analog stick values are within the dead zone

    /*if (abs(xVal) < mThreshold)
    {
      xVal = 0;
    }
    if (abs(yVal) < mThreshold)
    {
      yVal = 0;
    }*/

    motor[motorD] = ((yVal) + (xVal)) * scaleFactor;      //Sets left motor power
    motor[motorE] = ((yVal) - (xVal)) * scaleFactor;      //Sets right motor power

    //if(joy1Btn(1) == 1 && !isDropping){
    //	isDropping = true;
    //	//servo[servo1] = 120;
    //	servoLower(5);
    //	wait1Msec(500);
    //}
    //if(joy1Btn(2) == 1 && isDropping){
    //	isDropping = false;
    //	servo[servo1] = 0;
    //	wait1Msec(500);
    //}

    if(joy1Btn(2) == 1){
    	motor[motorTray] = 20;
    } else if (joy1Btn(4) == 1){
    	motor[motorTray] = -20;
    } else{
    	motor[motorTray] = 0;
    }

    //Controls launcher
    //if(joy1Btn(1) == 1 && isLaunching == false){
    	//isLaunching = true;
    	//fireLauncher();
    	//isLaunching = false;
    //}
	//wait1Msec(1);
  }
}
