#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     ,               sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v1.h"
#include "hitechnic-irseeker-v2.h"
#include "hitechnic-sensormux.h"


task main()
{
	//motor[motorD] = 10;
	//motor[motorE] = 10;
	//int _dirDC = 0;
	int _dirAC = 0;
	//int dcs1, dcs2, dcs3, dcs4, dcs5 = 0;
	int acs1, acs2, acs3, acs4, acs5 = 0;
	int maxSig = 0;
	int val = 0;

	tHTIRS2DSPMode _mode = DSP_1200;
	//HTIRS2setDSPMode(HTIRS2, _mode);
	/*
	while(true){
		acs2 = sensorValue[S2];
		if(acs2!=0){
			if(acs2 < 5){
				motor[motorE] = 10;
				motor[motorD] = -10;
			}
			if(acs2 == 5){
				motor[motorD] = 0;
				motor[motorE] = 0;
			}
			if (acs2 > 5){
				motor[motorD] = 10;
				motor[motorE] = -10;
			}
		}
		writeDebugStream("It is %d", acs2);
		writeDebugStream("\n");
		wait1Msec(5);
	}
*/
	while(true){
		//acs1 = HTIRS2_AC_SSTR1;
		HTIRS2readAllACStrength
		if(SensorValue[S1] = HTIRS2readACDir(HTIRS2){
		HTIRS2realAllACStrength(HTIRS2, acs1, acs2, acs3, acs4, acs5);
	}
	}
}
