#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorSONAR)
#pragma config(Sensor, S3,     HTGyro,         sensorAnalogInactive)
#pragma config(Sensor, S4,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  motorA,          motorGrabA,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motorGrabB,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     collector,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //Joystick is included in this program

task main()
{
  int threshold = 15; //to avoid unnecessary movement

  while(true) //infinite loop
  {
    getJoystickSettings(joystick); //retrieves data from the joystick
		if(joy1Btn(4) == 1){
    	motor[motorGrabA] = 100;
    	motor[motorGrabB] = 100;
    } else {
    	motor[motorGrabA] = 0;
    	motor[motorGrabB] = 0;
    }
    if(joy1Btn(2) == 1){
    	motor[motorGrabA] = -40;
    	motor[motorGrabB] = -40;
    } else {
    	motor[motorGrabA] = 0;
    	motor[motorGrabB] = 0;
    }
    if(abs(joystick.joy1_y1) > threshold)
    {
      motor[motorD] = (joystick.joy1_y1)/3; //y1 controller moves motorD
    }
    else
    {
      motor[motorD] = 0;
    }

    if(abs(joystick.joy1_y2) > threshold)
    {
      motor[motorE] = (joystick.joy1_y2)/3; //y2 controller moves motorE
    }
    else
    {
      motor[motorE] = 0;
    }
	}
}
