#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //Joystick is included in this program

task main()
{
  int threshold = 15; //to avoid unnecessary movement

  while(true) //infinite loop
  {
    getJoystickSettings(joystick); //retrieves data from the joystick

    if(abs(joystick.joy1_y1) > threshold)
    {
      motor[motorD] = (joystick.joy1_y1)/3; //y1 controller moves motorD
    }
    else
    {
      motor[motorD] = 0;
    }

    if(abs(joystick.joy1_y2) > threshold)
    {
      motor[motorE] = (joystick.joy1_y2)/3; //y2 controller moves motorE
    }
    else
    {
      motor[motorE] = 0;
    }
	}
}
