#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //Joystick is included in this program

void print(int s){
	NXTDisplayBigTextLine(3, "%d", s);
}

task main()
{
	int threshold = 5; //to avoid unnecessary movement
	int xVal, yVal;
	//waitForStart();
	while(true) //infinite loop
	{
		//print(1)
		getJoystickSettings(joystick); //retrieves data from the joystick

		if(abs(joystick.joy1_y1) > threshold || abs(joystick.joy1_x1) > threshold)
		{
		yVal = -joystick.joy1_x1;
    xVal = joystick.joy1_y1;
    motor[motorD] = ((yVal) + (xVal) * 3)/3;      //Sets left motor power
    motor[motorE] = ((yVal) - (xVal) * 3)/3;      //Sets right motor power
		print(2)
		}
		else
		{
			motor[motorD] = 0;
			motor[motorE] = 0;
			print(3)
		}
	}
}
