#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     ,               sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     ,               sensorSONAR)
#pragma config(Sensor, S4,     HTGyro,         sensorAnalogInactive)
#pragma config(Motor,  motorA,          motorTray,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-gyro.h"

void turnClockwise(int duration){
	motor[motorD]=15;
	motor[motorE]=-15;
	wait1Msec(duration);
	int a = SensorValue[S4];
	nxtDisplayBigStringAt(0, 31,"%d", a);
	motor[motorD]=0;
	motor[motorE]=0;
	wait1Msec(50);
}

void turnCounterClockwise(int duration){
	motor[motorD]=-15;
	motor[motorE]=15;
	wait1Msec(duration);
	motor[motorD]=0;
	motor[motorE]=0;
	wait1Msec(50);
}
void turnByDegreesClockwise(int degrees) {
	turnClockwise(degrees*11);
}
void turnByDegreesCounterClockwise(int degrees) {
	turnCounterClockwise(degrees*11);
}
task main()
{

	while(true){
	 //int a = HTIRS2readACDir(irSeeker);
		HTGYROstartCal(HTGYRO);
		turnClockwise(10000);
		wait10Msec(10);
	}
 //turnByDegreesClockwise(90);
}
